#!/bin/bash
set -eux
set -o pipefail

# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# Release a Debusine build from a ci child workspace into the target Debusine
# workspace

# Run directly inside the current job container. Debusine tooling is expected to
# be available already.

# Dependencies:
#   debusine-client, python3-debusine, yq

# Inputs:
#   DEBUSINE_HOST
#   DEBUSINE_SCOPE
#   DEBUSINE_TOKEN
#   DEBUSINE_CI_WORKSPACE
#   DEBUSINE_TARGET_WORKSPACE (optional, defaults to qli-staging)
#   SRCPKG_NAME
#   SRCPKG_VERSION
#   SUITE

# Outputs:
#   None

target_workspace=${DEBUSINE_TARGET_WORKSPACE:-qli-staging}

echo "::group::Release to Debusine ${target_workspace}"

mkdir -p ~/.config/debusine/client
( umask 077; cat > ~/.config/debusine/client/config.ini <<EOF
[General]
default-server = default

[server:default]
api-url = https://${DEBUSINE_HOST}/api
scope = ${DEBUSINE_SCOPE}
token = ${DEBUSINE_TOKEN}
default-workspace = ${target_workspace}
EOF
)

collection_list_output=$(debusine collection list -w "$DEBUSINE_CI_WORKSPACE" --yaml)
echo "Collection list output: $collection_list_output" >&2
suite_id=$(
  echo "$collection_list_output"|yq -r --arg suite "$SUITE" '
    map(select(.category == "debian:suite" and .name == $suite)) as $m
    | if ($m | length) == 1
      then $m[0].id
      else error("expected exactly one match")
      end
  '
)
workflow_start_output=$(debusine workflow start -w "${target_workspace}" --yaml package-publish <<END
source_artifact: ${suite_id}@collections/${SRCPKG_NAME}_${SRCPKG_VERSION}
binary_artifacts:
  category: debian:binary-package
  collection: ${suite_id}@collections
target_suite: ${SUITE}@debian:suite
unembargo: true
END
)
echo "Workflow start output: $workflow_start_output" >&2
workflow_id=$(echo "$workflow_start_output"|yq -r .id)
debusine-action/lib/poll_workflow.py "$workflow_id"

echo "::endgroup::"
