#!/usr/bin/env python3
#
# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
#
# SPDX-License-Identifier: BSD-3-Clause-Clear

"""
create_promotion_pr.py

Helper script to generate and open the promotion PR.
"""
import subprocess
import argparse
import sys
import traceback
from color_logger import logger

# This script is used to create the PR content of the promotion PR. Then, the actual PR is created using GitHub CLI
def parse_arguments():
    parser = argparse.ArgumentParser(description="Craft the content for a promotion PR and open it using GitHub CLI.")

    parser.add_argument("--base-branch",
                        required=False,
                        default="debian/qcom-next",
                        help="Base branch for the promotion PR.")

    parser.add_argument("--upstream-tag",
                        required=True,
                        help="Upstream tag corresponding to the version being promoted.")

    parser.add_argument("--normalized-version",
                        required=True,
                        help="Normalized version of the upstream project.")

    parser.add_argument("--promotion-version",
                        required=True,
                        help="Full Debian changelog version used for the promotion (for example 1.2.3-1 for Debian-bound branches, or 1.2.3-0qli1 for qli branches). This is also the suffix of the PR branch name debian/pr/<promotion-version>.")

    parser.add_argument("--promotion-pr-branch",
                        required=False,
                        default="",
                        help="Promotion PR branch name (for example debian/pr/1.2.3-0qli1_). If omitted, defaults to debian/pr/<promotion-version>.")

    parser.add_argument("--promoted-upstream-tag",
                        required=True,
                        help="Resolved promoted upstream tag created in the packaging repository (for example, upstream/1.2.3 or upstream/v1.2.3).")

    args = parser.parse_args()

    return args

def create_pr_title(normalized_version: str) -> str:
    return f"Promote to {normalized_version}"

def create_pr_body(base_branch: str, upstream_tag: str, promotion_version: str, promotion_pr_branch: str, promoted_upstream_tag: str) -> str:
    return f"""
## Automated promotion PR

This PR was generated by `pkg-promote` to move this package repo to upstream tag
`{upstream_tag}`.

### Summary

- Base branch: `{base_branch}`
- Upstream branch/tag prepared: `upstream/latest` / `{promoted_upstream_tag}`
- PR branch: `{promotion_pr_branch}`
- Changelog update: `{promotion_version}` (UNRELEASED)

### Reviewer checklist

1. Review the upstream merge and packaging diff.
2. Confirm the `Build` workflow is green.
3. If needed, push follow-up packaging fixes to this PR branch.
4. Merge with **Merge commit** (do not squash or rebase).

### Flow

```mermaid
---
config:
  themeVariables:
    'gitInv2': '#ff0000'
gitGraph:
  parallelCommits: true
  rotateCommitLabel: true
---
gitGraph BT:
  branch {base_branch}   order: 1
  branch upstream-main   order: 4
  branch upstream/latest order: 3
  checkout main
  commit id: 'Unrelated history: workflows, doc'
  checkout upstream-main
  commit
  checkout upstream-main
  commit
  commit id: 'release' tag: '{upstream_tag}'
  checkout upstream/latest
  commit id: 'previous stuff'
  merge upstream-main id: 'Filtered .github/debian folders' tag: '{promoted_upstream_tag}'
  checkout {base_branch}
  commit
  commit
  commit
  branch {promotion_pr_branch} order: 2
  merge upstream/latest id: 'Merged Upstream'
  commit id: 'Changelog version update' type: HIGHLIGHT
```
"""
    
def main():
    args = parse_arguments()

    logger.debug(f"Print of the arguments: {args}")

    promotion_pr_branch = args.promotion_pr_branch or f"debian/pr/{args.promotion_version}"

    pr_title = create_pr_title(args.normalized_version)
    pr_body = create_pr_body(
        args.base_branch,
        args.upstream_tag,
        args.promotion_version,
        promotion_pr_branch,
        args.promoted_upstream_tag,
    )

    # Printing the pr body in a .md file for manual review:
    with open("promotion_pr_body.md", "w") as pr_body_file:
        pr_body_file.write(pr_body)

    pr_creation_command = [
        "gh", "pr", "create",
        "--title", pr_title,
        "--body-file", "promotion_pr_body.md",
        "--base", args.base_branch,
        "--head", promotion_pr_branch,
    ]

    # Executing the PR creation command using GitHub CLI 
    subprocess.run(pr_creation_command, check=True)
        

if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        logger.critical(f"Uncaught exception : {e}")
        traceback.print_exc()
        sys.exit(1)
